apiVersion: apps/v1
kind: Deployment
metadata:
  name: local-llm-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: local-llm-service
  template:
    metadata:
      labels:
        app: local-llm-service
    spec:
      containers:
        - name: local-llm-service
          image: pratyushmohitk/nautilus:latest
          ports:
            - containerPort: 8888
          resources:
            requests:
              cpu: "500m"  # Request 0.5 CPU core
              memory: "512Mi"  # Request 512MB of RAM
            limits:
              cpu: "1000m"  # Limit to 1 CPU core
              memory: "1Gi"  # Limit to 1GB of RAM
